# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='qtd_pessoas',
            field=models.IntegerField(verbose_name='Rendimento'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.TimeField(verbose_name='Tempo de preparo'),
        ),
    ]
