# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170425_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='qtd_pessoas',
            new_name='rendimento',
        ),
    ]
